// ignore_for_file: avoid_print
//
// Emits the data files of the native Swift and Kotlin ports from this
// package's constants, so every table and every Arabic string in those ports
// is byte-identical to the Dart source of truth.
//
// Usage (from the package root):
//
//   dart run tool/generate_native_data.dart \
//     --swift  ../islamic_kit_swift/Sources/IslamicKitPlus \
//     --kotlin ../islamic_kit_android/core/src/main/kotlin/io/github/bilalelsayed97/islamickit
//
// Either flag may be omitted. Generated files carry a "do not edit" header and
// are safe to regenerate at any time.
//
// The generated code targets these hand-written declarations in each port:
//   Swift:  Language (.en/.ar), MidnightMode, Coordinates(_:_:),
//           MethodAdjustments(fajr:sunrise:dhuhr:asr:maghrib:isha:) with 0
//           defaults, MethodParams(fajrAngle:ishaAngle:ishaMinutesAfterMaghrib:
//           ramadanIshaMinutesAfterMaghrib:maghribAngle:maghribMinutesAfterSunset:
//           adjustments:midnightMode:location:) with Dart defaults, and the
//           other eight enums with Dart-named cases.
//   Kotlin: Language (EN/AR), MidnightMode, Coordinates(latitude, longitude),
//           MethodAdjustments / MethodParams data classes with the same named
//           parameters and defaults, the `Localized` interface, and the other
//           eight enums with UPPER_SNAKE entries.

import 'dart:io';

import 'package:islamic_kit_plus/islamic_kit_plus.dart';
import 'package:islamic_kit_plus/src/infrastructure/calendar/data/diyanet_table.dart';
import 'package:islamic_kit_plus/src/infrastructure/calendar/data/hijri_holidays.dart';
import 'package:islamic_kit_plus/src/infrastructure/calendar/data/hijri_sightings.dart';
import 'package:islamic_kit_plus/src/infrastructure/calendar/data/umm_al_qura_table.dart';
import 'package:islamic_kit_plus/src/infrastructure/geocoding/data/city_dataset.dart';
import 'package:islamic_kit_plus/src/infrastructure/geocoding/data/country_iso_map.dart';

const String _header =
    '// Generated by islamic_kit_plus tool/generate_native_data.dart — DO NOT EDIT.\n'
    '// Regenerate from the Dart package; every literal here mirrors the Dart source.\n';

const String _kotlinPackage = 'io.github.bilalelsayed97.islamickit';

void main(List<String> args) {
  String? swiftDir;
  String? kotlinDir;
  for (var i = 0; i < args.length; i++) {
    switch (args[i]) {
      case '--swift':
        swiftDir = args[++i];
      case '--kotlin':
        kotlinDir = args[++i];
      default:
        stderr.writeln('Unknown argument: ${args[i]}');
        exit(64);
    }
  }
  if (swiftDir == null && kotlinDir == null) {
    stderr.writeln('Pass --swift <dir> and/or --kotlin <dir>.');
    exit(64);
  }
  if (swiftDir != null) _generateSwift(swiftDir);
  if (kotlinDir != null) _generateKotlin(kotlinDir);
}

// -----------------------------------------------------------------------------
// Shared helpers
// -----------------------------------------------------------------------------

void _write(String dir, String relative, String content) {
  final file = File('$dir/$relative');
  file.parent.createSync(recursive: true);
  file.writeAsStringSync(content);
  print('wrote ${file.path}');
}

String _swiftStr(String s) =>
    '"${s.replaceAll(r'\', r'\\').replaceAll('"', r'\"')}"';

String _kotlinStr(String s) => '"${s.replaceAll(r'\', r'\\').replaceAll('"', r'\"').replaceAll(r'$', r'\$')}"';

/// `middleOfNight` -> `MIDDLE_OF_NIGHT`, `h12NoSuffix` -> `H12_NO_SUFFIX`.
String _upperSnake(String camel) {
  final buffer = StringBuffer();
  for (final rune in camel.runes) {
    final ch = String.fromCharCode(rune);
    if (ch.toUpperCase() == ch && ch.toLowerCase() != ch) buffer.write('_');
    buffer.write(ch.toUpperCase());
  }
  return buffer.toString();
}

String _intRows(List<int> values, {int perLine = 20, String indent = '    '}) {
  final buffer = StringBuffer();
  for (var i = 0; i < values.length; i += perLine) {
    final end = i + perLine > values.length ? values.length : i + perLine;
    buffer
      ..write(indent)
      ..write(values.sublist(i, end).join(', '))
      ..writeln(',');
  }
  return buffer.toString();
}

/// One localized enum: its native type name and every value's Dart name plus
/// the four strings.
class _L10nEnum {
  _L10nEnum(this.typeName, this.values);
  final String typeName;
  final List<_L10nValue> values;
}

class _L10nValue {
  _L10nValue(this.dartName, this.titleEn, this.titleAr, this.descEn,
      this.descAr);
  final String dartName;
  final String titleEn;
  final String titleAr;
  final String descEn;
  final String descAr;
}

List<_L10nEnum> _localizedEnums() => <_L10nEnum>[
      _L10nEnum('AsrSchool', [
        for (final v in AsrSchool.values)
          _L10nValue(v.name, v.title(Language.en), v.title(Language.ar),
              v.description(Language.en), v.description(Language.ar)),
      ]),
      _L10nEnum('MidnightMode', [
        for (final v in MidnightMode.values)
          _L10nValue(v.name, v.title(Language.en), v.title(Language.ar),
              v.description(Language.en), v.description(Language.ar)),
      ]),
      _L10nEnum('HighLatitudeRule', [
        for (final v in HighLatitudeRule.values)
          _L10nValue(v.name, v.title(Language.en), v.title(Language.ar),
              v.description(Language.en), v.description(Language.ar)),
      ]),
      _L10nEnum('Shafaq', [
        for (final v in Shafaq.values)
          _L10nValue(v.name, v.title(Language.en), v.title(Language.ar),
              v.description(Language.en), v.description(Language.ar)),
      ]),
      _L10nEnum('CalendarMethod', [
        for (final v in CalendarMethod.values)
          _L10nValue(v.name, v.title(Language.en), v.title(Language.ar),
              v.description(Language.en), v.description(Language.ar)),
      ]),
      _L10nEnum('TimeFormat', [
        for (final v in TimeFormat.values)
          _L10nValue(v.name, v.title(Language.en), v.title(Language.ar),
              v.description(Language.en), v.description(Language.ar)),
      ]),
      _L10nEnum('Prayer', [
        for (final v in Prayer.values)
          _L10nValue(v.name, v.title(Language.en), v.title(Language.ar),
              v.description(Language.en), v.description(Language.ar)),
      ]),
      _L10nEnum('Language', [
        for (final v in Language.values)
          _L10nValue(v.name, v.title(Language.en), v.title(Language.ar),
              v.description(Language.en), v.description(Language.ar)),
      ]),
    ];

// -----------------------------------------------------------------------------
// Swift
// -----------------------------------------------------------------------------

void _generateSwift(String dir) {
  _write(dir, 'Infrastructure/Calendar/Data/UmmAlQuraTable.swift',
      _swiftIntTable('UmmAlQuraTable', kUmmAlQuraTable));
  _write(dir, 'Infrastructure/Calendar/Data/DiyanetTable.swift',
      _swiftIntTable('DiyanetTable', kDiyanetTable));
  _write(dir, 'Infrastructure/Calendar/Data/HijriHolidays.swift',
      _swiftHolidays());
  _write(dir, 'Infrastructure/Calendar/Data/HijriSightings.swift',
      _swiftSightings());
  _write(dir, 'Infrastructure/Geocoding/Data/CityDataset.swift',
      _swiftCityDataset());
  _write(dir, 'Infrastructure/Geocoding/Data/CountryIsoMap.swift',
      _swiftCountryIsoMap());
  _write(dir, 'Infrastructure/Localization/Localizer.swift', _swiftLocalizer());
  _write(dir, 'Domain/Enums/CalculationMethod.swift', _swiftCalculationMethod());
  _write(dir, 'Domain/Enums/EnumLocalization.swift', _swiftEnumLocalization());
}

String _swiftIntTable(String typeName, List<int> data) => '''
$_header
/// Modified Chronological Julian Day Number (CJDN − 2,400,000) of the first
/// day of each lunar month, one entry per lunation. ${data.length} entries.
enum $typeName {
    static let data: [Int] = [
${_intRows(data, indent: '        ')}    ]
}
''';

String _swiftHolidays() {
  final buffer = StringBuffer()
    ..write(_header)
    ..writeln()
    ..writeln('/// Islamic holidays keyed by Hijri month, then day.')
    ..writeln('enum HijriHolidays {')
    ..writeln('    static let byMonth: [Int: [Int: [String]]] = [');
  for (final month in kHijriHolidays.entries) {
    buffer.writeln('        ${month.key}: [');
    for (final day in month.value.entries) {
      buffer.writeln(
          '            ${day.key}: [${day.value.map(_swiftStr).join(', ')}],');
    }
    buffer.writeln('        ],');
  }
  buffer
    ..writeln('    ]')
    ..writeln('}');
  return buffer.toString();
}

String _swiftSightings() {
  final buffer = StringBuffer()
    ..write(_header)
    ..writeln()
    ..writeln('/// HJCoSA announced lunar-sighting overrides: Gregorian `dd-mm-yyyy` ->')
    ..writeln('/// announced Hijri `dd-mm-yyyy`.')
    ..writeln('enum HijriSightings {')
    ..writeln('    static let gregorianToHijri: [String: String] = [');
  for (final e in kHjcosaSightings.entries) {
    buffer.writeln('        ${_swiftStr(e.key)}: ${_swiftStr(e.value)},');
  }
  buffer
    ..writeln('    ]')
    ..writeln()
    ..writeln('    /// The inverse map (all announced values are distinct).')
    ..writeln('    static let hijriToGregorian: [String: String] =')
    ..writeln('        Dictionary(uniqueKeysWithValues: gregorianToHijri.map { (\$1, \$0) })')
    ..writeln('}');
  return buffer.toString();
}

String _swiftCityDataset() {
  final buffer = StringBuffer()
    ..write(_header)
    ..writeln()
    ..writeln('/// A curated city record: name, ISO-3166 alpha-2 country, optional state,')
    ..writeln('/// coordinates and the city\'s **standard-time** UTC offset in minutes.')
    ..writeln('public struct CityRecord: Hashable, Sendable {')
    ..writeln('    public let name: String')
    ..writeln('    public let country: String')
    ..writeln('    public let state: String?')
    ..writeln('    public let lat: Double')
    ..writeln('    public let lng: Double')
    ..writeln('    public let offsetMinutes: Int')
    ..writeln()
    ..writeln('    public init(name: String, country: String, state: String?, lat: Double, lng: Double, offsetMinutes: Int) {')
    ..writeln('        self.name = name')
    ..writeln('        self.country = country')
    ..writeln('        self.state = state')
    ..writeln('        self.lat = lat')
    ..writeln('        self.lng = lng')
    ..writeln('        self.offsetMinutes = offsetMinutes')
    ..writeln('    }')
    ..writeln('}')
    ..writeln()
    ..writeln('/// The curated, offline city set behind `BundledCityGeocoder`.')
    ..writeln('public enum CityDataset {')
    ..writeln('    /// ${kCityDataset.length} major world cities (capitals + large cities).')
    ..writeln('    public static let records: [CityRecord] = [');
  for (final r in kCityDataset) {
    final state = r.state == null ? 'nil' : _swiftStr(r.state!);
    buffer.writeln(
        '        CityRecord(name: ${_swiftStr(r.name)}, country: ${_swiftStr(r.country)}, state: $state, lat: ${r.lat}, lng: ${r.lng}, offsetMinutes: ${r.offsetMinutes}),');
  }
  buffer
    ..writeln('    ]')
    ..writeln()
    ..writeln('    /// Lower-case common country names -> ISO-3166 alpha-2 codes.')
    ..writeln('    public static let countryAliases: [String: String] = [');
  for (final e in kCountryAliases.entries) {
    buffer.writeln('        ${_swiftStr(e.key)}: ${_swiftStr(e.value)},');
  }
  buffer
    ..writeln('    ]')
    ..writeln('}');
  return buffer.toString();
}

String _swiftCountryIsoMap() {
  final buffer = StringBuffer()
    ..write(_header)
    ..writeln()
    ..writeln('/// The bundled database\'s integer `country_id` <-> ISO 3166-1 alpha-2 mapping.')
    ..writeln('public enum CountryIsoMap {')
    ..writeln('    /// ${kCountryIdToIso.length} entries; id 103 is absent in the database.')
    ..writeln('    public static let idToIso: [Int: String] = [');
  for (final e in kCountryIdToIso.entries) {
    buffer.writeln('        ${e.key}: ${_swiftStr(e.value)},');
  }
  buffer
    ..writeln('    ]')
    ..writeln()
    ..writeln('    /// The inverse of `idToIso`.')
    ..writeln('    public static let isoToId: [String: Int] =')
    ..writeln('        Dictionary(uniqueKeysWithValues: idToIso.map { (\$1, \$0) })')
    ..writeln()
    ..writeln('    /// Time zones whose standard offset is not a whole hour. The database')
    ..writeln('    /// stores whole hours, so these override the stored value (in minutes).')
    ..writeln('    public static let fractionalZoneOffsetMinutes: [String: Int] = [');
  for (final e in kFractionalZoneOffsetMinutes.entries) {
    buffer.writeln('        ${_swiftStr(e.key)}: ${e.value},');
  }
  buffer
    ..writeln('    ]')
    ..writeln('}');
  return buffer.toString();
}

String _swiftLocalizedTable(String name, String doc, Map<int, LocalizedName> table) {
  final buffer = StringBuffer()
    ..writeln('    /// $doc')
    ..writeln('    public static let $name: [Int: LocalizedName] = [');
  for (final e in table.entries) {
    buffer.writeln(
        '        ${e.key}: LocalizedName(en: ${_swiftStr(e.value.en)}, ar: ${_swiftStr(e.value.ar)}),');
  }
  buffer.writeln('    ]');
  return buffer.toString();
}

String _swiftLocalizer() {
  final buffer = StringBuffer()
    ..write(_header)
    ..writeln()
    ..writeln('/// A localized (English + Arabic) name pair.')
    ..writeln('public struct LocalizedName: Hashable, Sendable {')
    ..writeln('    public let en: String')
    ..writeln('    public let ar: String')
    ..writeln()
    ..writeln('    public init(en: String, ar: String) {')
    ..writeln('        self.en = en')
    ..writeln('        self.ar = ar')
    ..writeln('    }')
    ..writeln('}')
    ..writeln()
    ..writeln('/// Static English/Arabic name tables for Gregorian and Hijri calendars.')
    ..writeln('///')
    ..writeln('/// Weekdays are keyed by ISO weekday number (Mon = 1 … Sun = 7).')
    ..writeln('public enum Localizer {')
    ..write(_swiftLocalizedTable('islamicMonths', 'Hijri months 1..12.', Localizer.islamicMonths))
    ..writeln()
    ..write(_swiftLocalizedTable('hijriWeekdays', 'Hijri weekday names keyed by ISO weekday (Mon = 1 … Sun = 7).', Localizer.hijriWeekdays))
    ..writeln()
    ..write(_swiftLocalizedTable('gregorianMonths', 'Gregorian months 1..12.', Localizer.gregorianMonths))
    ..writeln()
    ..write(_swiftLocalizedTable('gregorianWeekdays', 'Gregorian weekday names keyed by ISO weekday (Mon = 1 … Sun = 7).', Localizer.gregorianWeekdays))
    ..writeln()
    ..writeln('    /// English three-letter month abbreviations, index 0 = January.')
    ..writeln('    public static let monthAbbrEn: [String] = [${Localizer.monthAbbrEn.map(_swiftStr).join(', ')}]')
    ..writeln()
    ..writeln('    /// Hijri weekday name for an ISO weekday (Mon = 1 … Sun = 7).')
    ..writeln('    public static func hijriWeekday(_ isoWeekday: Int) -> LocalizedName {')
    ..writeln('        hijriWeekdays[isoWeekday]!')
    ..writeln('    }')
    ..writeln()
    ..writeln('    /// Gregorian weekday name for an ISO weekday (Mon = 1 … Sun = 7).')
    ..writeln('    public static func gregorianWeekday(_ isoWeekday: Int) -> LocalizedName {')
    ..writeln('        gregorianWeekdays[isoWeekday]!')
    ..writeln('    }')
    ..writeln('}');
  return buffer.toString();
}

String _swiftMethodParams(MethodParams p) {
  final args = <String>['fajrAngle: ${p.fajrAngle}'];
  if (p.ishaAngle != null) args.add('ishaAngle: ${p.ishaAngle}');
  if (p.ishaMinutesAfterMaghrib != null) {
    args.add('ishaMinutesAfterMaghrib: ${p.ishaMinutesAfterMaghrib}');
  }
  if (p.ramadanIshaMinutesAfterMaghrib != null) {
    args.add(
        'ramadanIshaMinutesAfterMaghrib: ${p.ramadanIshaMinutesAfterMaghrib}');
  }
  if (p.maghribAngle != null) args.add('maghribAngle: ${p.maghribAngle}');
  if (p.maghribMinutesAfterSunset != null) {
    args.add('maghribMinutesAfterSunset: ${p.maghribMinutesAfterSunset}');
  }
  if (!p.adjustments.isEmpty) {
    final a = p.adjustments;
    final fields = <String>[
      if (a.fajr != 0) 'fajr: ${a.fajr}',
      if (a.sunrise != 0) 'sunrise: ${a.sunrise}',
      if (a.dhuhr != 0) 'dhuhr: ${a.dhuhr}',
      if (a.asr != 0) 'asr: ${a.asr}',
      if (a.maghrib != 0) 'maghrib: ${a.maghrib}',
      if (a.isha != 0) 'isha: ${a.isha}',
    ];
    args.add('adjustments: MethodAdjustments(${fields.join(', ')})');
  }
  if (p.midnightMode != null) args.add('midnightMode: .${p.midnightMode!.name}');
  if (p.location != null) {
    args.add(
        'location: Coordinates(${p.location!.latitude}, ${p.location!.longitude})');
  }
  return 'MethodParams(${args.join(', ')})';
}

String _swiftCalculationMethod() {
  final buffer = StringBuffer()
    ..write(_header)
    ..writeln()
    ..writeln('/// A prayer-time calculation method (twilight authority).')
    ..writeln('///')
    ..writeln('/// Each method carries its numeric `id` (the raw value) and short `code`, a')
    ..writeln('/// human-readable `methodName`, and its strongly-typed `params`. Methods with')
    ..writeln('/// ids 1–23 keep the numbering of the aladhan API; the regional authorities')
    ..writeln('/// aladhan does not publish are numbered from 101 so the id spaces never')
    ..writeln('/// collide. Cases are declared in the Dart package\'s order, so `allCases`')
    ..writeln('/// matches `CalculationMethod.values`.')
    ..writeln('public enum CalculationMethod: Int, CaseIterable, Sendable {');
  for (final m in CalculationMethod.values) {
    buffer.writeln('    case ${m.name} = ${m.id}');
  }
  buffer
    ..writeln()
    ..writeln('    /// Numeric id (aladhan id for ids <= 99).')
    ..writeln('    public var id: Int { rawValue }')
    ..writeln()
    ..writeln('    /// Short upper-case code, e.g. `"MWL"`.')
    ..writeln('    public var code: String { descriptor.code }')
    ..writeln()
    ..writeln('    /// Human-readable authority name.')
    ..writeln('    public var methodName: String { descriptor.methodName }')
    ..writeln()
    ..writeln('    /// The method\'s twilight parameters and published corrections.')
    ..writeln('    public var params: MethodParams { descriptor.params }')
    ..writeln()
    ..writeln('    /// Whether Fajr/Isha are bounded by the Moonsighting Committee twilight.')
    ..writeln('    public var usesMoonsighting: Bool { descriptor.usesMoonsighting }')
    ..writeln()
    ..writeln('    /// Whether `id` is an aladhan method id (ids above 99 are package extensions).')
    ..writeln('    public var isAladhanMethod: Bool { id <= 99 }')
    ..writeln()
    ..writeln('    /// Looks a method up by id, falling back to `.mwl`.')
    ..writeln('    public static func fromId(_ id: Int) -> CalculationMethod {')
    ..writeln('        CalculationMethod(rawValue: id) ?? .mwl')
    ..writeln('    }')
    ..writeln()
    ..writeln('    /// Looks a method up by code, falling back to `.mwl`.')
    ..writeln('    public static func fromCode(_ code: String) -> CalculationMethod {')
    ..writeln('        allCases.first { \$0.code == code } ?? .mwl')
    ..writeln('    }')
    ..writeln()
    ..writeln('    /// Short UI label for `language`.')
    ..writeln('    public func title(_ language: Language) -> String {')
    ..writeln('        switch self {');
  for (final m in CalculationMethod.values) {
    buffer.writeln(
        '        case .${m.name}: return language == .ar ? ${_swiftStr(m.title(Language.ar))} : ${_swiftStr(m.title(Language.en))}');
  }
  buffer
    ..writeln('        }')
    ..writeln('    }')
    ..writeln()
    ..writeln('    /// One-sentence description for `language`.')
    ..writeln('    public func description(_ language: Language) -> String {')
    ..writeln('        switch self {');
  for (final m in CalculationMethod.values) {
    buffer.writeln(
        '        case .${m.name}: return language == .ar ? ${_swiftStr(m.description(Language.ar))} : ${_swiftStr(m.description(Language.en))}');
  }
  buffer
    ..writeln('        }')
    ..writeln('    }')
    ..writeln()
    ..writeln('    private var descriptor: MethodDescriptor { Self.descriptors[self]! }')
    ..writeln()
    ..writeln('    private static let descriptors: [CalculationMethod: MethodDescriptor] =')
    ..writeln('        Dictionary(uniqueKeysWithValues: allCases.map { (\$0, makeDescriptor(\$0)) })')
    ..writeln()
    ..writeln('    // One statement per case keeps type-checking linear.')
    ..writeln('    private static func makeDescriptor(_ method: CalculationMethod) -> MethodDescriptor {')
    ..writeln('        switch method {');
  for (final m in CalculationMethod.values) {
    buffer
      ..writeln('        case .${m.name}:')
      ..writeln('            return MethodDescriptor(')
      ..writeln('                code: ${_swiftStr(m.code)},')
      ..writeln('                methodName: ${_swiftStr(m.methodName)},')
      ..writeln('                params: ${_swiftMethodParams(m.params)},')
      ..writeln('                usesMoonsighting: ${m.usesMoonsighting})');
  }
  buffer
    ..writeln('        }')
    ..writeln('    }')
    ..writeln('}')
    ..writeln()
    ..writeln('/// The per-method data behind `CalculationMethod`\'s computed properties.')
    ..writeln('struct MethodDescriptor: Sendable {')
    ..writeln('    let code: String')
    ..writeln('    let methodName: String')
    ..writeln('    let params: MethodParams')
    ..writeln('    let usesMoonsighting: Bool')
    ..writeln('}');
  return buffer.toString();
}

String _swiftEnumLocalization() {
  final buffer = StringBuffer()
    ..write(_header)
    ..writeln()
    ..writeln('// End-user localization (title + description) for every enum except')
    ..writeln('// `CalculationMethod`, which carries its own.');
  for (final e in _localizedEnums()) {
    buffer
      ..writeln()
      ..writeln('extension ${e.typeName} {')
      ..writeln('    /// Short UI label for `language`.')
      ..writeln('    public func title(_ language: Language) -> String {')
      ..writeln('        switch self {');
    for (final v in e.values) {
      buffer.writeln(
          '        case .${v.dartName}: return language == .ar ? ${_swiftStr(v.titleAr)} : ${_swiftStr(v.titleEn)}');
    }
    buffer
      ..writeln('        }')
      ..writeln('    }')
      ..writeln()
      ..writeln('    /// One-sentence description for `language`.')
      ..writeln('    public func description(_ language: Language) -> String {')
      ..writeln('        switch self {');
    for (final v in e.values) {
      buffer.writeln(
          '        case .${v.dartName}: return language == .ar ? ${_swiftStr(v.descAr)} : ${_swiftStr(v.descEn)}');
    }
    buffer
      ..writeln('        }')
      ..writeln('    }')
      ..writeln('}');
  }
  return buffer.toString();
}

// -----------------------------------------------------------------------------
// Kotlin
// -----------------------------------------------------------------------------

void _generateKotlin(String dir) {
  _write(dir, 'infrastructure/calendar/data/UmmAlQuraTable.kt',
      _kotlinIntTable('UmmAlQuraTable', kUmmAlQuraTable));
  _write(dir, 'infrastructure/calendar/data/DiyanetTable.kt',
      _kotlinIntTable('DiyanetTable', kDiyanetTable));
  _write(dir, 'infrastructure/calendar/data/HijriHolidays.kt', _kotlinHolidays());
  _write(dir, 'infrastructure/calendar/data/HijriSightings.kt',
      _kotlinSightings());
  _write(dir, 'infrastructure/geocoding/data/CityDataset.kt',
      _kotlinCityDataset());
  _write(dir, 'infrastructure/geocoding/data/CountryIsoMap.kt',
      _kotlinCountryIsoMap());
  _write(dir, 'infrastructure/localization/Localizer.kt', _kotlinLocalizer());
  _write(dir, 'domain/enums/CalculationMethod.kt', _kotlinCalculationMethod());
  _write(dir, 'domain/enums/EnumStrings.kt', _kotlinEnumStrings());
}

String _kotlinIntTable(String typeName, List<int> data) => '''
$_header
package $_kotlinPackage.infrastructure.calendar.data

/**
 * Modified Chronological Julian Day Number (CJDN − 2,400,000) of the first day
 * of each lunar month, one entry per lunation. ${data.length} entries.
 */
internal object $typeName {
    @JvmField
    val data: IntArray = intArrayOf(
${_intRows(data, indent: '        ')}    )
}
''';

String _kotlinHolidays() {
  final buffer = StringBuffer()
    ..write(_header)
    ..writeln()
    ..writeln('package $_kotlinPackage.infrastructure.calendar.data')
    ..writeln()
    ..writeln('/** Islamic holidays keyed by Hijri month, then day. */')
    ..writeln('internal object HijriHolidays {')
    ..writeln('    @JvmField')
    ..writeln('    val byMonth: Map<Int, Map<Int, List<String>>> = mapOf(');
  for (final month in kHijriHolidays.entries) {
    buffer.writeln('        ${month.key} to mapOf(');
    for (final day in month.value.entries) {
      buffer.writeln(
          '            ${day.key} to listOf(${day.value.map(_kotlinStr).join(', ')}),');
    }
    buffer.writeln('        ),');
  }
  buffer
    ..writeln('    )')
    ..writeln('}');
  return buffer.toString();
}

String _kotlinSightings() {
  final buffer = StringBuffer()
    ..write(_header)
    ..writeln()
    ..writeln('package $_kotlinPackage.infrastructure.calendar.data')
    ..writeln()
    ..writeln('/**')
    ..writeln(' * HJCoSA announced lunar-sighting overrides: Gregorian `dd-mm-yyyy` ->')
    ..writeln(' * announced Hijri `dd-mm-yyyy`.')
    ..writeln(' */')
    ..writeln('internal object HijriSightings {')
    ..writeln('    @JvmField')
    ..writeln('    val gregorianToHijri: Map<String, String> = linkedMapOf(');
  for (final e in kHjcosaSightings.entries) {
    buffer.writeln('        ${_kotlinStr(e.key)} to ${_kotlinStr(e.value)},');
  }
  buffer
    ..writeln('    )')
    ..writeln()
    ..writeln('    /** The inverse map (all announced values are distinct). */')
    ..writeln('    @JvmField')
    ..writeln('    val hijriToGregorian: Map<String, String> =')
    ..writeln('        gregorianToHijri.entries.associate { (gregorian, hijri) -> hijri to gregorian }')
    ..writeln('}');
  return buffer.toString();
}

String _kotlinCityDataset() {
  final buffer = StringBuffer()
    ..write(_header)
    ..writeln()
    ..writeln('package $_kotlinPackage.infrastructure.geocoding.data')
    ..writeln()
    ..writeln('/**')
    ..writeln(' * A curated city record: name, ISO-3166 alpha-2 country, optional state,')
    ..writeln(' * coordinates and the city\'s **standard-time** UTC offset in minutes.')
    ..writeln(' */')
    ..writeln('data class CityRecord(')
    ..writeln('    val name: String,')
    ..writeln('    val country: String,')
    ..writeln('    val state: String?,')
    ..writeln('    val lat: Double,')
    ..writeln('    val lng: Double,')
    ..writeln('    val offsetMinutes: Int,')
    ..writeln(')')
    ..writeln()
    ..writeln('/** The curated, offline city set behind `BundledCityGeocoder`. */')
    ..writeln('object CityDataset {')
    ..writeln('    /** ${kCityDataset.length} major world cities (capitals + large cities). */')
    ..writeln('    @JvmField')
    ..writeln('    val records: List<CityRecord> = listOf(');
  for (final r in kCityDataset) {
    final state = r.state == null ? 'null' : _kotlinStr(r.state!);
    buffer.writeln(
        '        CityRecord(${_kotlinStr(r.name)}, ${_kotlinStr(r.country)}, $state, ${r.lat}, ${r.lng}, ${r.offsetMinutes}),');
  }
  buffer
    ..writeln('    )')
    ..writeln()
    ..writeln('    /** Lower-case common country names -> ISO-3166 alpha-2 codes. */')
    ..writeln('    @JvmField')
    ..writeln('    val countryAliases: Map<String, String> = linkedMapOf(');
  for (final e in kCountryAliases.entries) {
    buffer.writeln('        ${_kotlinStr(e.key)} to ${_kotlinStr(e.value)},');
  }
  buffer
    ..writeln('    )')
    ..writeln('}');
  return buffer.toString();
}

String _kotlinCountryIsoMap() {
  final buffer = StringBuffer()
    ..write(_header)
    ..writeln()
    ..writeln('package $_kotlinPackage.infrastructure.geocoding.data')
    ..writeln()
    ..writeln('/** The bundled database\'s integer `country_id` <-> ISO 3166-1 alpha-2 mapping. */')
    ..writeln('object CountryIsoMap {')
    ..writeln('    /** ${kCountryIdToIso.length} entries; id 103 is absent in the database. */')
    ..writeln('    @JvmField')
    ..writeln('    val idToIso: Map<Int, String> = linkedMapOf(');
  for (final e in kCountryIdToIso.entries) {
    buffer.writeln('        ${e.key} to ${_kotlinStr(e.value)},');
  }
  buffer
    ..writeln('    )')
    ..writeln()
    ..writeln('    /** The inverse of [idToIso]. */')
    ..writeln('    @JvmField')
    ..writeln('    val isoToId: Map<String, Int> = idToIso.entries.associate { (id, iso) -> iso to id }')
    ..writeln()
    ..writeln('    /**')
    ..writeln('     * Time zones whose standard offset is not a whole hour. The database stores')
    ..writeln('     * whole hours, so these override the stored value (in minutes).')
    ..writeln('     */')
    ..writeln('    @JvmField')
    ..writeln('    val fractionalZoneOffsetMinutes: Map<String, Int> = linkedMapOf(');
  for (final e in kFractionalZoneOffsetMinutes.entries) {
    buffer.writeln('        ${_kotlinStr(e.key)} to ${e.value},');
  }
  buffer
    ..writeln('    )')
    ..writeln('}');
  return buffer.toString();
}

String _kotlinLocalizedTable(String name, String doc, Map<int, LocalizedName> table) {
  final buffer = StringBuffer()
    ..writeln('    /** $doc */')
    ..writeln('    @JvmField')
    ..writeln('    val $name: Map<Int, LocalizedName> = linkedMapOf(');
  for (final e in table.entries) {
    buffer.writeln(
        '        ${e.key} to LocalizedName(${_kotlinStr(e.value.en)}, ${_kotlinStr(e.value.ar)}),');
  }
  buffer.writeln('    )');
  return buffer.toString();
}

String _kotlinLocalizer() {
  final buffer = StringBuffer()
    ..write(_header)
    ..writeln()
    ..writeln('package $_kotlinPackage.infrastructure.localization')
    ..writeln()
    ..writeln('/** A localized (English + Arabic) name pair. */')
    ..writeln('data class LocalizedName(val en: String, val ar: String)')
    ..writeln()
    ..writeln('/**')
    ..writeln(' * Static English/Arabic name tables for Gregorian and Hijri calendars.')
    ..writeln(' *')
    ..writeln(' * Weekdays are keyed by ISO weekday number (Mon = 1 … Sun = 7).')
    ..writeln(' */')
    ..writeln('object Localizer {')
    ..write(_kotlinLocalizedTable('islamicMonths', 'Hijri months 1..12.', Localizer.islamicMonths))
    ..writeln()
    ..write(_kotlinLocalizedTable('hijriWeekdays', 'Hijri weekday names keyed by ISO weekday (Mon = 1 … Sun = 7).', Localizer.hijriWeekdays))
    ..writeln()
    ..write(_kotlinLocalizedTable('gregorianMonths', 'Gregorian months 1..12.', Localizer.gregorianMonths))
    ..writeln()
    ..write(_kotlinLocalizedTable('gregorianWeekdays', 'Gregorian weekday names keyed by ISO weekday (Mon = 1 … Sun = 7).', Localizer.gregorianWeekdays))
    ..writeln()
    ..writeln('    /** English three-letter month abbreviations, index 0 = January. */')
    ..writeln('    @JvmField')
    ..writeln('    val monthAbbrEn: List<String> = listOf(${Localizer.monthAbbrEn.map(_kotlinStr).join(', ')})')
    ..writeln()
    ..writeln('    /** Hijri weekday name for an ISO weekday (Mon = 1 … Sun = 7). */')
    ..writeln('    @JvmStatic')
    ..writeln('    fun hijriWeekday(isoWeekday: Int): LocalizedName = hijriWeekdays.getValue(isoWeekday)')
    ..writeln()
    ..writeln('    /** Gregorian weekday name for an ISO weekday (Mon = 1 … Sun = 7). */')
    ..writeln('    @JvmStatic')
    ..writeln('    fun gregorianWeekday(isoWeekday: Int): LocalizedName = gregorianWeekdays.getValue(isoWeekday)')
    ..writeln('}');
  return buffer.toString();
}

String _kotlinMethodParams(MethodParams p) {
  final args = <String>['fajrAngle = ${p.fajrAngle}'];
  if (p.ishaAngle != null) args.add('ishaAngle = ${p.ishaAngle}');
  if (p.ishaMinutesAfterMaghrib != null) {
    args.add('ishaMinutesAfterMaghrib = ${p.ishaMinutesAfterMaghrib}');
  }
  if (p.ramadanIshaMinutesAfterMaghrib != null) {
    args.add(
        'ramadanIshaMinutesAfterMaghrib = ${p.ramadanIshaMinutesAfterMaghrib}');
  }
  if (p.maghribAngle != null) args.add('maghribAngle = ${p.maghribAngle}');
  if (p.maghribMinutesAfterSunset != null) {
    args.add('maghribMinutesAfterSunset = ${p.maghribMinutesAfterSunset}');
  }
  if (!p.adjustments.isEmpty) {
    final a = p.adjustments;
    final fields = <String>[
      if (a.fajr != 0) 'fajr = ${a.fajr}',
      if (a.sunrise != 0) 'sunrise = ${a.sunrise}',
      if (a.dhuhr != 0) 'dhuhr = ${a.dhuhr}',
      if (a.asr != 0) 'asr = ${a.asr}',
      if (a.maghrib != 0) 'maghrib = ${a.maghrib}',
      if (a.isha != 0) 'isha = ${a.isha}',
    ];
    args.add('adjustments = MethodAdjustments(${fields.join(', ')})');
  }
  if (p.midnightMode != null) {
    args.add('midnightMode = MidnightMode.${_upperSnake(p.midnightMode!.name)}');
  }
  if (p.location != null) {
    args.add(
        'location = Coordinates(${p.location!.latitude}, ${p.location!.longitude})');
  }
  return 'MethodParams(${args.join(', ')})';
}

String _kotlinCalculationMethod() {
  final buffer = StringBuffer()
    ..write(_header)
    ..writeln()
    ..writeln('package $_kotlinPackage.domain.enums')
    ..writeln()
    ..writeln('import $_kotlinPackage.domain.valueobjects.Coordinates')
    ..writeln('import $_kotlinPackage.domain.valueobjects.MethodAdjustments')
    ..writeln('import $_kotlinPackage.domain.valueobjects.MethodParams')
    ..writeln()
    ..writeln('/**')
    ..writeln(' * A prayer-time calculation method (twilight authority).')
    ..writeln(' *')
    ..writeln(' * Each method carries its numeric [id] and short [code], a human-readable')
    ..writeln(' * [methodName], and its strongly-typed [params]. Methods with ids 1–23 keep the')
    ..writeln(' * numbering of the aladhan API; the regional authorities aladhan does not')
    ..writeln(' * publish are numbered from 101 so the two id spaces never collide. Entries are')
    ..writeln(' * declared in the Dart package\'s order, so [entries] matches')
    ..writeln(' * `CalculationMethod.values`.')
    ..writeln(' */')
    ..writeln('enum class CalculationMethod(')
    ..writeln('    /** Numeric id (aladhan id for ids <= 99). */')
    ..writeln('    val id: Int,')
    ..writeln('    /** Short upper-case code, e.g. `"MWL"`. */')
    ..writeln('    val code: String,')
    ..writeln('    /** Human-readable authority name. */')
    ..writeln('    val methodName: String,')
    ..writeln('    /** The method\'s twilight parameters and published corrections. */')
    ..writeln('    val params: MethodParams,')
    ..writeln('    /** Whether Fajr/Isha are bounded by the Moonsighting Committee twilight. */')
    ..writeln('    val usesMoonsighting: Boolean = false,')
    ..writeln(') : Localized {');
  const methods = CalculationMethod.values;
  for (var i = 0; i < methods.length; i++) {
    final m = methods[i];
    final args = <String>[
      '${m.id}',
      _kotlinStr(m.code),
      _kotlinStr(m.methodName),
      _kotlinMethodParams(m.params),
      if (m.usesMoonsighting) 'usesMoonsighting = true',
    ];
    final terminator = i == methods.length - 1 ? ';' : ',';
    buffer
      ..writeln('    ${_upperSnake(m.name)}(')
      ..writeln('        ${args.join(',\n        ')},')
      ..writeln('    )$terminator');
  }
  buffer
    ..writeln()
    ..writeln('    /** Whether [id] is an aladhan method id (ids above 99 are package extensions). */')
    ..writeln('    val isAladhanMethod: Boolean')
    ..writeln('        get() = id <= 99')
    ..writeln()
    ..writeln('    override fun title(language: Language): String = when (this) {');
  for (final m in methods) {
    buffer.writeln(
        '        ${_upperSnake(m.name)} -> if (language == Language.AR) ${_kotlinStr(m.title(Language.ar))} else ${_kotlinStr(m.title(Language.en))}');
  }
  buffer
    ..writeln('    }')
    ..writeln()
    ..writeln('    override fun description(language: Language): String = when (this) {');
  for (final m in methods) {
    buffer.writeln(
        '        ${_upperSnake(m.name)} -> if (language == Language.AR) ${_kotlinStr(m.description(Language.ar))} else ${_kotlinStr(m.description(Language.en))}');
  }
  buffer
    ..writeln('    }')
    ..writeln()
    ..writeln('    companion object {')
    ..writeln('        /** Looks a method up by id, falling back to [MWL]. */')
    ..writeln('        @JvmStatic')
    ..writeln('        fun fromId(id: Int): CalculationMethod = entries.firstOrNull { it.id == id } ?: MWL')
    ..writeln()
    ..writeln('        /** Looks a method up by code, falling back to [MWL]. */')
    ..writeln('        @JvmStatic')
    ..writeln('        fun fromCode(code: String): CalculationMethod = entries.firstOrNull { it.code == code } ?: MWL')
    ..writeln('    }')
    ..writeln('}');
  return buffer.toString();
}

String _kotlinEnumStrings() {
  final buffer = StringBuffer()
    ..write(_header)
    ..writeln()
    ..writeln('package $_kotlinPackage.domain.enums')
    ..writeln()
    ..writeln('/**')
    ..writeln(' * End-user localization (title + description) for every enum except')
    ..writeln(' * [CalculationMethod], which carries its own. Enums delegate their')
    ..writeln(' * [Localized] members here.')
    ..writeln(' */')
    ..writeln('internal object EnumStrings {');
  var first = true;
  for (final e in _localizedEnums()) {
    if (!first) buffer.writeln();
    first = false;
    buffer.writeln('    fun title(value: ${e.typeName}, language: Language): String = when (value) {');
    for (final v in e.values) {
      buffer.writeln(
          '        ${e.typeName}.${_upperSnake(v.dartName)} -> if (language == Language.AR) ${_kotlinStr(v.titleAr)} else ${_kotlinStr(v.titleEn)}');
    }
    buffer
      ..writeln('    }')
      ..writeln()
      ..writeln('    fun description(value: ${e.typeName}, language: Language): String = when (value) {');
    for (final v in e.values) {
      buffer.writeln(
          '        ${e.typeName}.${_upperSnake(v.dartName)} -> if (language == Language.AR) ${_kotlinStr(v.descAr)} else ${_kotlinStr(v.descEn)}');
    }
    buffer.writeln('    }');
  }
  buffer.writeln('}');
  return buffer.toString();
}
